### ISSUE TITLE
Console Errors When Developing

### ISSUE THREAD

**Issue by jessedelira** [jessedelira/gym-tracker#27]
**Describe the bug**
A new icon was added to the settings page and doesn't have the correct attributes naming conventions that are used in other icons.

**To Reproduce**
1. Start development server
2. Go to the settings page (make sure to have your console open in your browser dev tools)
3. See the errors appear (image pasted below)

**Expected behavior**
Expected behavior is to not have console error that are preventable while developing gym tracker.

**Screenshots**
<img width="2249" alt="image" src="https://github.com/jessedelira/gym-tracker/assets/38845310/7d4ec659-9509-4566-8e23-dd686f206a4a">

**Comment by noelbarrera** [comment]
If you haven't committed anything to the branch you made, I can take this off your hands. 😄
