### ISSUE TITLE
Move Navbar from the top of the screen to the bottom.

### ISSUE THREAD

**Issue by noelbarrera** [jessedelira/gym-tracker#30]
**Is your feature request related to a problem? Please describe.**
A user might find it more comfortable and natural for the navbar to be at the bottom of the screen.

**Describe the solution you'd like**
Where ever the navbar component is used move it to the bottom of the page.

**Describe alternatives you've considered**
The only reasonable alternative is to keep it where it currently is. 

**Additional context**
N/A

**Comment by jessedelira** [comment]
It might also be a good idea to add just creating a layout for the project along with this issue. We can have the layout always have the NavBar at the bottom and the content above it regardless of the page. This will help with use not needing place the NavBar component at the bottom of each Next Page
